version: '3.9'
services:
  web:
    build: .
    image: &img web_image
    command: python manage.py runserver 0.0.0.0:8000
    env_file: &env
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - worker

  worker:
    build: .
    image: *img
    command: [celery, -A, audio_slicer, worker, --loglevel=INFO]
    env_file: *env
    depends_on:
      - rabbitmq
    restart: 'no'

  rabbitmq:
    image: rabbitmq:3.7.8
